name: "{{ cookiecutter.marketplace_name }}"
description: "{{ cookiecutter.project_name }}"

inputs:
  placeholder:
    description: "Placeholder input to be replaced by real inputs"
    required: true
    default: "placeholder"

outputs:
  placeholder:
    description: "Placeholder output to be replaced by real outputs"
{%- if cookiecutter.action_type == 'composite' %}
    value: ${{ "{{" }}steps.placeholder.outputs.placeholder }}
{%- endif %}
{%- if cookiecutter.action_type == 'composite' %}

runs:
  using: "composite"
  steps:
    - name: Placeholder
      id: placeholder
      shell: bash
      run: |
        echo "::set-output name=placeholder::${{ "{{" }} inputs.placeholder }}"
{%- endif %}
{%- if cookiecutter.action_type == 'node' %}

runs:
  using: node24
  main: dist/index.js
{%- endif %}

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "message-square"
  color: "gray-dark"
