name: E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ "{{" }} github.workflow }}-${{ "{{" }} github.event.number }}
  cancel-in-progress: true

jobs:
  e2e-default:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          placeholder: "test_placeholder"

      - name: Assert placeholder
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ "{{" }} steps.test-run.outputs.placeholder }}
          expected: "test_placeholder"
  e2e:
    runs-on: ubuntu-latest
    if: always() && !cancelled()

    needs:
      - e2e-default

    steps:
      - name: Collect Results
        uses: ovsds/collect-needs-result-action@v1
        with:
          needs_json: ${{ "{{" }} toJson(needs) }}
          skip_allowed: false
