name: E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  e2e-default:
    runs-on: ubuntu-20.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Run
        id: test-run
        uses: ./
        with:
          placeholder: "test_placeholder"

      - name: Assert placeholder
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ "{{" }} steps.test-run.outputs.placeholder }}
          expected: "test_placeholder"
