name: Push version tags

on:
  release:
    types: [published]

concurrency:
  group: ${{ "{{" }} github.workflow }}
  cancel-in-progress: false

jobs:
  push-version-tags:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Push Version Tags
        uses: ovsds/push-version-tags-action@v1
        with:
          version: ${{ "{{" }} github.event.release.tag_name }}
