name: "Setup Environment"
description: "Setting environment for the project"

inputs:
  task-version:
    description: "Task version"
    required: true
    default: "3.33.1"
  task-enabled:
    description: "Task enabled"
    required: true
    default: "true"
{%- if cookiecutter.with_zizmor == 'true' %}
  zizmor-version:
    description: "Zizmor version"
    required: true
    default: "1.0.1"
  zizmor-enabled:
    description: "Zizmor enabled"
    required: true
    default: "false"
{%- endif %}

runs:
  using: "composite"
  steps:
    - name: Setup Task
      if: ${{ "{{" }} inputs.task-enabled == 'true' }}
      uses: arduino/setup-task@v2.0.0
      with:
        version: ${{ "{{" }} inputs.task-version }}
{%- if cookiecutter.with_zizmor == 'true' %}

    - name: Setup Zizmor
      if: ${{ "{{" }} inputs.zizmor-enabled == 'true' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install "zizmor==${ZIZMOR_VERSION}"
      env:
        ZIZMOR_VERSION: ${{ "{{" }} inputs.zizmor-version }}
{%- endif %}
